### ISSUE TITLE
跟之前的ampq 配置文件互不影响还是怎么样？

### ISSUE THREAD

**Issue by hejiaqiang1980** [hooklife/hyperf-aliyun-amqp#1]
跟之前的ampq 配置文件互不影响还是怎么样？ 现在打开就报错

[ERROR] PhpAmqpLib\Exception\AMQPRuntimeException:Error receiving data, errno=110(0) in /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php:176

目前配置文件如下 其它都是官网文档ampq demo代码

config/ampq.php

return [
    'default' => [
        'host' => 'xxxxxx.mq-amqp.cn-shenzhen-a.aliyuncs.com',
        'port' => 5672,
        'vhost' => 'test1',
        'concurrent' => [
            'limit' => 1,
        ],
        'pool' => [
            'min_connections' => 1,
            'max_connections' => 10,
            'connect_timeout' => 10.0,
            'wait_timeout' => 3.0,
            'heartbeat' => -1,
        ],
        'params' => [
            'insist' => false,
            'login_method' => 'AMQPLAIN',
            'login_response' => null,
            'locale' => 'en_US',
            'connection_timeout' => 3.0,
            'read_write_timeout' => 3.0,
            'context' => null,
            'keepalive' => false,
            'heartbeat' => 0,
        ],
    ],
];

aliyun_ampq.php

return [
    'default' => [
        'endpoint'          => 'xxxx.mq-amqp.cn-shenzhen-a.aliyuncs.com',
        'owner_id'          => 'xxx',
        'access_key_id'     => 'xxx',
        'access_key_secret' => 'xxx',
    ],
];

从阿里云控制台可以看到 是正常连通过的

**Comment by hooklife** [comment]
报错信息太少了
https://github.com/hooklife/hyperf-aliyun-amqp/blob/70a5a36ba58c50f9f1e64757631a1efef18fd82a/src/AliyunAmqpConnectionPool.php#L32
帮我在这行 var_dump 一下 $this->config 看下是正常的么？

**Comment by hejiaqiang1980** [comment]
array(8) {
  ["host"]=>
  string(51) "xxx.mq-amqp.cn-shenzhen-a.aliyuncs.com"
  ["port"]=>
  int(5672)
  ["vhost"]=>
  string(5) "xxx"
  ["concurrent"]=>
  array(1) {
    ["limit"]=>
    int(1)
  }
  ["pool"]=>
  array(5) {
    ["min_connections"]=>
    int(1)
    ["max_connections"]=>
    int(10)
    ["connect_timeout"]=>
    float(10)
    ["wait_timeout"]=>
    float(3)
    ["heartbeat"]=>
    int(-1)
  }
  ["params"]=>
  array(9) {
    ["insist"]=>
    bool(false)
    ["login_method"]=>
    string(8) "AMQPLAIN"
    ["login_response"]=>
    NULL
    ["locale"]=>
    string(5) "en_US"
    ["connection_timeout"]=>
    float(3)
    ["read_write_timeout"]=>
    float(3)
    ["context"]=>
    NULL
    ["keepalive"]=>
    bool(false)
    ["heartbeat"]=>
    int(0)
  }
  ["user"]=>
  string(48) "xxx"
  ["password"]=>
  string(72) "xxx"
}

**Comment by hejiaqiang1980** [comment]
完整报错信息

[ERROR] PhpAmqpLib\Exception\AMQPRuntimeException:Error receiving data, errno=110(0) in /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php:176
Stack trace:
#0 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(165): Hyperf\Amqp\Connection\SwooleIO->read(7)
#1 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(562): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(619): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(234): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#5 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(352): PhpAmqpLib\Channel\AbstractChannel->next_frame(0)
#6 /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Consumer.php(89): PhpAmqpLib\Channel\AbstractChannel->wait()
#7 /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/ConsumerManager.php(80): Hyperf\Amqp\Consumer->consume(Object(App\Amqp\Consumer\DemoConsumer))
#8 /mnt/hgfs/web/hyperf/vendor/hyperf/process/src/AbstractProcess.php(113): class@anonymous->handle()
#9 {main}
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php:174
Stack trace:
#0 /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php(174): Swoole\Coroutine\Client->recv(3)
#1 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(165): Hyperf\Amqp\Connection\SwooleIO->read(7)
#2 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#3 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(562): PhpAmqpLib\Wire\AMQPReader->read(7)
#4 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(619): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#5 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(234): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#6 /mnt/hgfs/web/hyperf/vendor/php-amq in /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php on line 174

Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php:174
Stack trace:
#0 /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php(174): Swoole\Coroutine\Client->recv(3)
#1 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(165): Hyperf\Amqp\Connection\SwooleIO->read(7)
#2 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#3 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(562): PhpAmqpLib\Wire\AMQPReader->read(7)
#4 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(619): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#5 /mnt/hgfs/web/hyperf/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(234): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#6 /mnt/hgfs/web/hyperf/vendor/php-amq in /mnt/hgfs/web/hyperf/vendor/hyperf/amqp/src/Connection/SwooleIO.php on line 174

**Comment by hooklife** [comment]
`API must be called in the coroutine`

你是改动框架部分代码了么？你不使用我的这个扩展直接链接 amqp 会报错么？

**Comment by hejiaqiang1980** [comment]
没改动框架呢 直接用 文档amqp里的示例代码 没自己独立用过amqp 我所有删了重新拉一遍试试。

**Comment by hejiaqiang1980** [comment]
配置文件还是跟之前一样
https://hyperf.wiki/#/zh/amqp
完整的跟着文档走
执行完 php bin/hyperf.php gen:amqp-consumer DemoConsumer
后 执行php bin/hyperf.php start
就报一样的错误

**Comment by hooklife** [comment]
swoole 的版本是多少

**Comment by hejiaqiang1980** [comment]
PHP Version 7.2.21
swoole Version | 4.4.8

**Comment by hooklife** [comment]
https://github.com/hyperf/hyperf/pull/976
close_on_destruct 这个配置改为 false
你试下

**Comment by hejiaqiang1980** [comment]
还是不行的

**Comment by hejiaqiang1980** [comment]
明白了 队列为空的时候报错 谢谢

**Comment by yupaker** [comment]
> 

遇到了同样的问题,请问是怎样解决的.  是由于队列超时导致的吗
